# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
    
    # Security checks
    - name: Checks 
      uses: securego/gosec@v2.18.2
    
    - name: Lint
      uses: golangci/golangci-lint-action@v4.0.0
  
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Release
      uses: goreleaser/goreleaser-action@master
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
